/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MainLoader */

#ifndef _Included_MainLoader
#define _Included_MainLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MainLoader
 * Method:    get
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MainLoader_get
  (JNIEnv *, jobject, jstring);

/*
 * Class:     MainLoader
 * Method:    put
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_MainLoader_put
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
